### PR TITLE
add privacy settings and importing active song list from other users 

### PR DESCRIPTION
**Pull request by mmccall0813**

### CODE REVIEW

**Review by McMistrzYT — CHANGES_REQUESTED** [review]
i wanted to do this but by using a user's id instead of a json so i'll use your pr as a base

**Comment by McMistrzYT** [comment]
rework the json part to just be able to paste a user's discord id

**Comment by mmccall0813** [comment]
will add a privacy settings menu when i get home from work

**Comment by mmccall0813** [comment]
added privacy settings menu and the ability to import from discord id. might need some style tweaking, im not a fan of where i put the import button but idk where else to put it

**Review by McMistrzYT — APPROVED** [review]

**Pull request merged**
